server:
  port: 8980
spring:
  application:
    name: gateway-microservice
    cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  cloud:
    gateway:
      routes:
#        - id: home-microservice
#          uri: lb://HOME-MICROSERVICE
#          predicates:
#            - Path=/api/admin/rest/**
#        - id: home-microservice
#          uri: lb://HOME-MICROSERVICE
#          predicates:
#            - Path=/api/user/rest/**
        - id: admin-microservice
          uri: lb://ADMIN-MICROSERVICE
          predicates:
            - Path=/api/admin/**
        - id: user-microservice
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/api/user/**
eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
